CREATE TABLE IF NOT EXISTS USERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    PASSWORD VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS OFFER_UPLOAD (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ORG_CIF_NAME VARCHAR(200),

    MIN_TENURE_DAYS INT NOT NULL,
    MAX_TENURE_DAYS INT NOT NULL,

    PRODUCT_CODE VARCHAR(50) NOT NULL,

    VALID_FROM DATE NOT NULL,
    VALID_TO DATE NOT NULL,

    OFFER_TYPE VARCHAR(30),

    R1 CHAR(1),
    R2 CHAR(1),
    R3 CHAR(1),

    R4_TEMPLATE VARCHAR(50),
    R4_1_1 CHAR(1),
    R4_1_2 CHAR(1),
    R4_2_1 CHAR(1),
    R4_2_2 CHAR(1),

    R5 CHAR(1),

    FIXED_RATE DECIMAL(5,2),
    REPO_RATE DECIMAL(5,2),
    MCLR_RATE DECIMAL(5,2),

    SOURCE_TYPE VARCHAR(30),
    DESCRIPTION VARCHAR(500),

    DIGITAL_WCDL CHAR(1),
    EWS_CHECK CHAR(1),
    PSL_STATUS CHAR(1),
    MSME_STATUS CHAR(1),

    LOB VARCHAR(30),

    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


